# Generated by Django 6.0.8 on 2026-08-29 17:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0002_rename_kind_state_index'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted', models.BooleanField(default=False)),
                ('kind', models.CharField(choices=[('MILESTONE', 'Milestone'), ('EXIT', 'Exit')], max_length=20)),
                ('state', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=20)),
                ('started_on', models.DateField(blank=True, null=True)),
                ('completed_on', models.DateField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='declarations', to='applications.application')),
                ('declared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='declarations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='DeclarationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted', models.BooleanField(default=False)),
                ('storage_key', models.CharField(editable=False, max_length=255)),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size', models.PositiveIntegerField()),
                ('sha256', models.CharField(editable=False, max_length=64)),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='declarations.declaration')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='declaration_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_date'],
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='DeclarationMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('MILESTONE', 'Milestone'), ('EXIT', 'Exit')], max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='milestone_claims', to='applications.application')),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='milestones', to='declarations.declaration')),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='declaration_claims', to='catalog.milestone')),
                ('superseded_by', models.ForeignKey(blank=True, help_text='Null while this is the current claim on the milestone.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supersedes', to='declarations.declaration')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.AddIndex(
            model_name='declaration',
            index=models.Index(fields=['application', '-created_date'], name='declarations_app_recent_idx'),
        ),
        migrations.AddConstraint(
            model_name='declaration',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['MILESTONE', 'EXIT'])), name='declarations_declaration_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='declaration',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['SUBMITTED', 'APPROVED', 'REJECTED'])), name='declarations_declaration_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='declaration',
            constraint=models.CheckConstraint(condition=models.Q(('started_on__isnull', True), ('completed_on__isnull', True), ('completed_on__gte', models.F('started_on')), _connector='OR'), name='declarations_declaration_dates_ordered'),
        ),
        migrations.AddConstraint(
            model_name='declarationdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('storage_key',), name='declarations_document_unique_storage_key'),
        ),
        migrations.AddIndex(
            model_name='declarationmilestone',
            index=models.Index(fields=['application', 'kind'], name='declarations_claim_app_idx'),
        ),
        migrations.AddConstraint(
            model_name='declarationmilestone',
            constraint=models.UniqueConstraint(condition=models.Q(('superseded_by__isnull', True)), fields=('application', 'kind', 'milestone'), name='declarations_one_current_claim'),
        ),
        migrations.AddConstraint(
            model_name='declarationmilestone',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['MILESTONE', 'EXIT'])), name='declarations_milestone_kind_valid'),
        ),
    ]
