# Generated by Django 6.0.8 on 2026-08-29 09:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("modified_date", models.DateTimeField(auto_now=True, db_index=True)),
                ("deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("ORGANIZATION", "Organization"),
                            ("INDIVIDUAL", "Individual"),
                        ],
                        max_length=20,
                    ),
                ),
                ("website", models.URLField(blank=True)),
                ("address_line1", models.CharField(blank=True, max_length=255)),
                ("address_line2", models.CharField(blank=True, max_length=255)),
                ("address_city", models.CharField(blank=True, max_length=100)),
                ("address_pincode", models.CharField(blank=True, max_length=10)),
                ("lgd_state_code", models.CharField(blank=True, max_length=10)),
                ("lgd_district_code", models.CharField(blank=True, max_length=10)),
                (
                    "verification_state",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("VERIFIED", "Verified")],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organisations_verified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "default_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("modified_date", models.DateTimeField(auto_now=True, db_index=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "role",
                    models.CharField(
                        choices=[("OWNER", "Owner"), ("DEVELOPER", "Developer")],
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "default_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("modified_date", models.DateTimeField(auto_now=True, db_index=True)),
                ("deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "default_manager_name": "objects",
            },
        ),
        migrations.AddConstraint(
            model_name="organisation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted", False)),
                fields=("slug",),
                name="organisations_organisation_unique_slug",
            ),
        ),
        migrations.AddConstraint(
            model_name="organisation",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ["ORGANIZATION", "INDIVIDUAL"])),
                name="organisations_organisation_kind_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="organisation",
            constraint=models.CheckConstraint(
                condition=models.Q(("verification_state__in", ["PENDING", "VERIFIED"])),
                name="organisations_organisation_verification_state_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted", False)),
                fields=("organisation", "user"),
                name="organisations_membership_unique_organisation_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.CheckConstraint(
                condition=models.Q(("role__in", ["OWNER", "DEVELOPER"])),
                name="organisations_membership_role_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted", False)),
                fields=("organisation", "slug"),
                name="organisations_product_unique_organisation_slug",
            ),
        ),
    ]
