# Generated by Django 6.0.8 on 2026-08-18 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Organisation')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('legal_name', models.CharField(blank=True, max_length=255, verbose_name='Legal entity name')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=120, verbose_name='State')),
                ('deployment_regions', models.TextField(blank=True, help_text='States/UTs where you deploy or plan to deploy Care.', verbose_name='Deployment regions')),
                ('technical_contact_name', models.CharField(blank=True, max_length=255, verbose_name='Technical contact name')),
                ('technical_contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Technical contact email')),
                ('verification_status', models.CharField(choices=[('pending', 'Verification pending'), ('verified', 'Verified vendor'), ('rejected', 'Verification rejected')], default='pending', max_length=20, verbose_name='Verification status')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verified at')),
                ('onboarded_at', models.DateTimeField(blank=True, null=True, verbose_name='Onboarded at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('developer', 'Developer'), ('support', 'Support')], default='developer', max_length=20, verbose_name='Role')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organisations.organisation', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Membership',
                'verbose_name_plural': 'Memberships',
                'ordering': [models.Case(models.When(role='owner', then=models.Value(0)), models.When(role='admin', then=models.Value(1)), models.When(role='developer', then=models.Value(2)), models.When(role='support', then=models.Value(3)), default=models.Value(4), output_field=models.PositiveSmallIntegerField()), 'user__name', 'user__email'],
                'constraints': [models.UniqueConstraint(fields=('organisation', 'user'), name='unique_membership_per_organisation')],
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('developer', 'Developer'), ('support', 'Support')], default='developer', max_length=20, verbose_name='Role')),
                ('token', models.CharField(editable=False, max_length=64, unique=True, verbose_name='Token')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Invited by')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='organisations.organisation', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Invitation',
                'verbose_name_plural': 'Invitations',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('accepted_at__isnull', True), ('revoked_at__isnull', True)), fields=('organisation', 'email'), name='unique_open_invitation_per_email')],
            },
        ),
    ]
