# Generated by Django 6.0.8 on 2026-08-29 12:15

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='category',
            field=models.CharField(blank=True, choices=[('CENTRAL_GOVERNMENT_PROGRAM', 'Central Government Program'), ('CENTRAL_GOVERNMENT_ENTITY_TMS', 'Central Government Entity - TMS'), ('DIAGNOSTIC_LABS', 'Diagnostic Labs'), ('NCD_PROGRAMME_GOI', 'For NCD Programme of GoI'), ('GOVERNMENT_HEALTH_LOCKER', 'Government Health Locker'), ('GOVERNMENT_HMIS_SOLUTION_PROVIDER', 'Government HMIS Solution Provider'), ('HEALTH_LOCKER', 'Health Locker'), ('HEALTHCARE_SOLUTION_PROVIDER', 'Healthcare Solution Provider'), ('HMIS', 'HMIS'), ('INSURANCE', 'Insurance'), ('PHARMACY', 'Pharmacy'), ('PSU', 'PSU'), ('STATE_GOVERNMENT_PROGRAM', 'State Government Program')], default='', max_length=40),
        ),
        migrations.AddField(
            model_name='organisation',
            name='gst_number',
            field=models.CharField(blank=True, default='', max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid 15-character GSTIN.', regex='^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]$')]),
        ),
        migrations.AddField(
            model_name='organisation',
            name='nature_of_entity',
            field=models.CharField(blank=True, choices=[('COMPANY', 'Company'), ('GOVERNMENT', 'Government'), ('LLP', 'LLP'), ('PARTNERSHIP_FIRM', 'Partnership Firm'), ('PROPRIETORSHIP_FIRM', 'Proprietorship Firm'), ('SOCIETY', 'Society'), ('TRUST', 'Trust')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='organisation',
            name='ownership',
            field=models.CharField(blank=True, choices=[('GOVERNMENT', 'Government'), ('PRIVATE', 'Private')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='organisation',
            name='registered_in_india',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddConstraint(
            model_name='organisation',
            constraint=models.CheckConstraint(condition=models.Q(('nature_of_entity__in', ['COMPANY', 'GOVERNMENT', 'LLP', 'PARTNERSHIP_FIRM', 'PROPRIETORSHIP_FIRM', 'SOCIETY', 'TRUST', ''])), name='organisations_organisation_nature_of_entity_valid'),
        ),
        migrations.AddConstraint(
            model_name='organisation',
            constraint=models.CheckConstraint(condition=models.Q(('ownership__in', ['GOVERNMENT', 'PRIVATE', ''])), name='organisations_organisation_ownership_valid'),
        ),
        migrations.AddConstraint(
            model_name='organisation',
            constraint=models.CheckConstraint(condition=models.Q(('category__in', ['CENTRAL_GOVERNMENT_PROGRAM', 'CENTRAL_GOVERNMENT_ENTITY_TMS', 'DIAGNOSTIC_LABS', 'NCD_PROGRAMME_GOI', 'GOVERNMENT_HEALTH_LOCKER', 'GOVERNMENT_HMIS_SOLUTION_PROVIDER', 'HEALTH_LOCKER', 'HEALTHCARE_SOLUTION_PROVIDER', 'HMIS', 'INSURANCE', 'PHARMACY', 'PSU', 'STATE_GOVERNMENT_PROGRAM', ''])), name='organisations_organisation_category_valid'),
        ),
    ]
