# Generated by Django 6.0.8 on 2026-08-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='technical_contact_phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Technical contact phone number'),
        ),
    ]
