# Generated by Django 6.0.8 on 2026-09-06 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0004_seed_review_roles'),
        ('organisations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvisioningRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('ready', 'Ready'), ('failed', 'Failed')], default='running', max_length=20, verbose_name='Status')),
                ('correlation_id', models.CharField(blank=True, max_length=64, verbose_name='Correlation id')),
                ('error', models.TextField(blank=True, verbose_name='Error')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provisioning_runs', to='experiences.applicationinstance', verbose_name='Application')),
                ('started_by', models.ForeignKey(blank=True, help_text='Null when the approval started it rather than a person.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provisioning_runs_started', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Provisioning run',
                'verbose_name_plural': 'Provisioning runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.DeleteModel(
            name='Sandbox',
        ),
    ]
