# Generated by Django 6.0.8 on 2026-08-19 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_organisation_technical_contact_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sandbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('provisioning', 'Provisioning'), ('ready', 'Ready'), ('failed', 'Failed')], default='requested', max_length=20, verbose_name='Status')),
                ('facility_name', models.CharField(blank=True, max_length=255, verbose_name='Facility name')),
                ('is_facility_empty', models.BooleanField(default=False, verbose_name='Empty facility')),
                ('job_id', models.CharField(blank=True, max_length=64, verbose_name='Plugin job id')),
                ('result', models.JSONField(blank=True, default=dict, verbose_name='Result')),
                ('error', models.TextField(blank=True, verbose_name='Error')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('provisioned_at', models.DateTimeField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sandbox', to='organisations.organisation', verbose_name='Organisation')),
                ('provisioned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provisioned_sandboxes', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_sandboxes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sandbox',
                'verbose_name_plural': 'Sandboxes',
                'ordering': ['-requested_at'],
            },
        ),
    ]
