# Generated by Django 6.0.8 on 2026-09-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_provisioningrun_delete_sandbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='category',
            field=models.CharField(blank=True, choices=[('CENTRAL_GOVERNMENT_PROGRAM', 'Central Government Program'), ('CENTRAL_GOVERNMENT_ENTITY_TMS', 'Central Government Entity - TMS'), ('DIAGNOSTIC_LABS', 'Diagnostic Labs'), ('NCD_PROGRAMME_GOI', 'For NCD Programme of GoI'), ('GOVERNMENT_HEALTH_LOCKER', 'Government Health Locker'), ('GOVERNMENT_HMIS_SOLUTION_PROVIDER', 'Government HMIS Solution Provider'), ('HEALTH_LOCKER', 'Health Locker'), ('HEALTHCARE_SOLUTION_PROVIDER', 'Healthcare Solution Provider'), ('HMIS', 'HMIS'), ('INSURANCE', 'Insurance'), ('PHARMACY', 'Pharmacy'), ('PSU', 'PSU'), ('STATE_GOVERNMENT_PROGRAM', 'State Government Program')], max_length=40, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='lgd_district_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='LGD district code'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='lgd_state_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='LGD state code'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='listing_hidden',
            field=models.BooleanField(default=False, verbose_name='Hidden from listing'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='mobile_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Mobile verified at'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='nature_of_entity',
            field=models.CharField(blank=True, choices=[('COMPANY', 'Company'), ('GOVERNMENT_BODY', 'Government Body'), ('INDIVIDUAL', 'Individual'), ('LLP', 'LLP'), ('PARTNERSHIP_FIRM', 'Partnership Firm'), ('PROPRIETORSHIP_FIRM', 'Proprietorship Firm'), ('SOCIETY', 'Society'), ('TRUST', 'Trust')], max_length=30, verbose_name='Nature of entity'),
        ),
        migrations.AddConstraint(
            model_name='organisation',
            constraint=models.CheckConstraint(condition=models.Q(('nature_of_entity__in', ['COMPANY', 'GOVERNMENT_BODY', 'INDIVIDUAL', 'LLP', 'PARTNERSHIP_FIRM', 'PROPRIETORSHIP_FIRM', 'SOCIETY', 'TRUST', ''])), name='organisations_organisation_nature_of_entity_valid'),
        ),
        migrations.AddConstraint(
            model_name='organisation',
            constraint=models.CheckConstraint(condition=models.Q(('category__in', ['CENTRAL_GOVERNMENT_PROGRAM', 'CENTRAL_GOVERNMENT_ENTITY_TMS', 'DIAGNOSTIC_LABS', 'NCD_PROGRAMME_GOI', 'GOVERNMENT_HEALTH_LOCKER', 'GOVERNMENT_HMIS_SOLUTION_PROVIDER', 'HEALTH_LOCKER', 'HEALTHCARE_SOLUTION_PROVIDER', 'HMIS', 'INSURANCE', 'PHARMACY', 'PSU', 'STATE_GOVERNMENT_PROGRAM', ''])), name='organisations_organisation_category_valid'),
        ),
    ]
