# Generated by Django 6.0.8 on 2026-09-06 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0004_seed_review_roles'),
        ('organisations', '0004_organisation_abdm_identity_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilestoneGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone', models.CharField(choices=[('m1', 'M1 - ABHA creation, capture and verification'), ('m2', 'M2 - HIP and consented health-record sharing'), ('m3', 'M3 - HIU and consented health-record access'), ('m4', 'M4 - NHPR professional and facility registration')], max_length=10, verbose_name='Milestone')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='Granted at')),
                ('roles_attached', models.JSONField(blank=True, default=list, verbose_name='Roles attached')),
                ('roles_attached_at', models.DateTimeField(blank=True, null=True, verbose_name='Roles attached at')),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='milestone_grants', to='experiences.applicationinstance', verbose_name='Granted by')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_grants', to='organisations.organisation', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Milestone grant',
                'verbose_name_plural': 'Milestone grants',
                'ordering': ['organisation', 'milestone'],
                'constraints': [models.UniqueConstraint(fields=('organisation', 'milestone'), name='organisations_milestone_grant_unique'), models.CheckConstraint(condition=models.Q(('milestone__in', ['m1', 'm2', 'm3', 'm4'])), name='organisations_milestone_grant_milestone_valid')],
            },
        ),
    ]
