# Generated by Django 6.0.8 on 2026-09-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0005_milestonegrant'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='ownership',
            field=models.CharField(blank=True, choices=[('GOVERNMENT', 'Government'), ('PRIVATE', 'Private')], max_length=20, verbose_name='Type of organisation'),
        ),
        migrations.AddConstraint(
            model_name='organisation',
            constraint=models.CheckConstraint(condition=models.Q(('ownership__in', ['GOVERNMENT', 'PRIVATE', ''])), name='organisations_organisation_ownership_valid'),
        ),
    ]
