# Generated by Django 6.0.8 on 2026-09-08 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0006_organisation_ownership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='organisations.organisation', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['organisation', 'name'],
                'constraints': [models.UniqueConstraint(fields=('organisation', 'slug'), name='organisations_product_unique_organisation_slug')],
            },
        ),
    ]
