# Generated by Django 6.0.8 on 2026-08-29 08:52

import uuid

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True,
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("modified_date", models.DateTimeField(auto_now=True, db_index=True)),
                ("deleted", models.BooleanField(default=False)),
                ("key", models.SlugField()),
                ("title", models.CharField(max_length=200)),
                ("track", models.CharField(max_length=50)),
                ("order", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["track", "order"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted", False)),
                        fields=("key",),
                        name="catalog_milestone_unique_key",
                    ),
                ],
            },
        ),
    ]
