# Generated by Django 6.0.8 on 2026-08-31 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='milestone',
            name='catalog_milestone_unique_key',
        ),
        migrations.DeleteModel(
            name='Milestone',
        ),
    ]
