# Generated by Django 6.0.8 on 2026-08-18 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('kind', models.CharField(choices=[('office_hours', 'Office hours'), ('webinar', 'Webinar'), ('ama', 'AMA'), ('workshop', 'Workshop')], default='webinar', max_length=20, verbose_name='Kind')),
                ('summary', models.CharField(blank=True, help_text='One line shown under the title on the dashboard.', max_length=255, verbose_name='Summary')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('starts_at', models.DateTimeField(verbose_name='Starts at')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Ends at')),
                ('location', models.CharField(blank=True, help_text='Leave blank for an online event.', max_length=255, verbose_name='Location')),
                ('join_url', models.URLField(blank=True, verbose_name='Join link')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, limit_choices_to={'is_ohc_team': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['starts_at'],
                'indexes': [models.Index(fields=['published_at', 'starts_at'], name='events_even_publish_26dca1_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_at__isnull', True), ('ends_at__gt', models.F('starts_at')), _connector='OR'), name='event_ends_after_it_starts')],
            },
        ),
    ]
