# Generated by Django 6.0.8 on 2026-08-29 13:09

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=100)),
                ('object_type', models.CharField(max_length=100)),
                ('object_external_id', models.UUIDField(blank=True, null=True)),
                ('correlation_id', models.CharField(blank=True, max_length=64)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['object_type', 'object_external_id'], name='audit_event_object_idx'), models.Index(fields=['action'], name='audit_event_action_idx'), django.contrib.postgres.indexes.BrinIndex(fields=['occurred_at'], name='audit_event_occurred_brin')],
            },
        ),
    ]
