# Generated by Django 6.0.8 on 2026-08-29 09:46

import uuid

import django.core.validators
from django.db import migrations
from django.db import models

BATCH = 500


def assign_external_ids(apps, schema_editor):
    """Give every existing row its own UUID.

    A single `AddField(default=uuid.uuid4, unique=True)` evaluates the default
    once and writes the same UUID to every row, so the unique index then fails
    to build. It succeeds on an empty database and on one holding a single user,
    which is why CI stayed green while staging would have broken mid-deploy.
    """
    user_model = apps.get_model("users", "User")
    batch = []
    for user in user_model.objects.filter(external_id__isnull=True).iterator(
        chunk_size=BATCH,
    ):
        user.external_id = uuid.uuid4()
        batch.append(user)
        if len(batch) >= BATCH:
            user_model.objects.bulk_update(batch, ["external_id"])
            batch.clear()
    if batch:
        user_model.objects.bulk_update(batch, ["external_id"])


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verified_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="email verified at",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                default="",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message=(
                            "Enter a phone number with 7-15 digits, optionally "
                            "starting with '+'."
                        ),
                        regex="^\\+?[0-9]{7,15}$",
                    ),
                ],
                verbose_name="phone number",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_verified_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="phone verified at",
            ),
        ),
        # Add nullable, backfill, then constrain: the one-step version cannot
        # populate rows that already exist.
        migrations.AddField(
            model_name="user",
            name="external_id",
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.RunPython(assign_external_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="user",
            name="external_id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                unique=True,
            ),
        ),
    ]
