# Generated by Django 6.0.8 on 2026-08-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_ohc_team',
            field=models.BooleanField(default=False, help_text='Works the support queue across all vendors and publishes events. Separate from staff status, which only controls Django admin access.', verbose_name='OHC team member'),
        ),
    ]
