# Generated by Django 6.0.8 on 2026-09-01 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_email_verified_at_user_external_id_user_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('manage_roles', 'Can create and edit console roles')]},
        ),
    ]
