# Generated by Django 6.0.8 on 2026-08-30 07:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0002_rename_kind_state_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvisionedResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted', models.BooleanField(default=False)),
                ('system', models.CharField(choices=[('KEYCLOAK', 'Keycloak'), ('WSO2', 'WSO2'), ('HIECM', 'HIE-CM')], max_length=20)),
                ('external_ref', models.CharField(max_length=255)),
                ('secret_ref', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(choices=[('ACTIVE', 'Active'), ('DISABLED', 'Disabled'), ('FAILED', 'Failed'), ('ORPHANED', 'Orphaned')], default='ACTIVE', max_length=20)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provisioned_resources', to='applications.application')),
            ],
            options={
                'indexes': [models.Index(fields=['system', 'state'], name='integrations_system_state_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('application', 'system'), name='integrations_provisioned_resource_unique_application_system'), models.CheckConstraint(condition=models.Q(('system__in', ['KEYCLOAK', 'WSO2', 'HIECM'])), name='integrations_provisioned_resource_system_valid'), models.CheckConstraint(condition=models.Q(('state__in', ['ACTIVE', 'DISABLED', 'FAILED', 'ORPHANED'])), name='integrations_provisioned_resource_state_valid')],
            },
        ),
    ]
