# Generated by Django 6.0.8 on 2026-08-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisionedresource',
            name='public_ref',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
