# Generated by Django 6.0.8 on 2026-09-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Reference')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('category', models.CharField(choices=[('sandbox', 'Sandbox'), ('api', 'API'), ('certification', 'Certification'), ('deployment', 'Deployment'), ('billing', 'Billing')], default='sandbox', max_length=20, verbose_name='Category')),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10, verbose_name='Priority')),
                ('status', models.CharField(choices=[('open', 'Open'), ('awaiting_vendor', 'Awaiting your reply'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20, verbose_name='Status')),
                ('linked_facility', models.CharField(blank=True, max_length=255, verbose_name='Linked facility')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_responded_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('reply', 'Reply'), ('event', 'Status change')], default='reply', max_length=10)),
                ('body', models.TextField(verbose_name='Message')),
                ('from_staff_team', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ticket message',
                'verbose_name_plural': 'Ticket messages',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
