# Generated by Django 6.0.8 on 2026-08-18 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0002_organisation_technical_contact_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Reference')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('category', models.CharField(choices=[('sandbox', 'Sandbox'), ('api', 'API'), ('certification', 'Certification'), ('deployment', 'Deployment'), ('billing', 'Billing')], default='sandbox', max_length=20, verbose_name='Category')),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10, verbose_name='Priority')),
                ('status', models.CharField(choices=[('open', 'Open'), ('awaiting_vendor', 'Awaiting your reply'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20, verbose_name='Status')),
                ('linked_facility', models.CharField(blank=True, max_length=255, verbose_name='Linked facility')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_responded_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('assignee', models.ForeignKey(blank=True, limit_choices_to={'is_ohc_team': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Assignee')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_opened', to=settings.AUTH_USER_MODEL, verbose_name='Opened by')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='organisations.organisation', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('reply', 'Reply'), ('event', 'Status change')], default='reply', max_length=10)),
                ('body', models.TextField(verbose_name='Message')),
                ('from_ohc_team', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_messages', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.ticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Ticket message',
                'verbose_name_plural': 'Ticket messages',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['organisation', '-updated_at'], name='support_tic_organis_b749fa_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', '-updated_at'], name='support_tic_status_5d73f8_idx'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(('resolved_at__isnull', True), ('resolved_at__gte', models.F('created_at')), _connector='OR'), name='ticket_resolved_after_created'),
        ),
    ]
