# Generated by Django 6.0.8 on 2026-08-29 11:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationReferenceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted', models.BooleanField(default=False)),
                ('reference', models.CharField(editable=False, max_length=15)),
                ('kind', models.CharField(choices=[('SANDBOX', 'Sandbox'), ('HCX', 'HCX'), ('UHI', 'UHI'), ('HIU', 'HIU'), ('NHCX', 'NHCX')], max_length=20)),
                ('state', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('SANDBOX_APPROVED', 'Sandbox approved'), ('PROVISIONING', 'Provisioning'), ('PROVISIONED', 'Provisioned'), ('PROVISIONING_FAILED', 'Provisioning failed'), ('REJECTED', 'Rejected'), ('SENT_BACK', 'Sent back'), ('EXIT_REQUESTED', 'Exit requested'), ('EXIT_REVIEW', 'Exit review'), ('PRODUCTION_APPROVED', 'Production approved'), ('EXIT_REJECTED', 'Exit rejected'), ('WITHDRAWN', 'Withdrawn')], default='DRAFT', max_length=30)),
                ('payload', models.JSONField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='organisations.product')),
            ],
            options={
                'default_manager_name': 'objects',
                'indexes': [models.Index(fields=['kind', 'state'], name='applications_application_kind_state_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('reference',), name='applications_application_unique_reference'), models.UniqueConstraint(condition=models.Q(('deleted', False), models.Q(('state__in', ('REJECTED', 'WITHDRAWN')), _negated=True)), fields=('product', 'kind'), name='applications_application_unique_live_product_kind'), models.CheckConstraint(condition=models.Q(('kind__in', ['SANDBOX', 'HCX', 'UHI', 'HIU', 'NHCX'])), name='applications_application_kind_valid'), models.CheckConstraint(condition=models.Q(('state__in', ['DRAFT', 'SUBMITTED', 'SANDBOX_APPROVED', 'PROVISIONING', 'PROVISIONED', 'PROVISIONING_FAILED', 'REJECTED', 'SENT_BACK', 'EXIT_REQUESTED', 'EXIT_REVIEW', 'PRODUCTION_APPROVED', 'EXIT_REJECTED', 'WITHDRAWN'])), name='applications_application_state_valid')],
            },
        ),
    ]
