# Generated by Django 6.0.8 on 2026-08-29 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='application',
            new_name='applications_kind_state_idx',
            old_name='applications_application_kind_state_idx',
        ),
    ]
