# Generated by Django 6.0.8 on 2026-08-31 16:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_rename_kind_state_index'),
        ('organisations', '0002_organisation_category_organisation_gst_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted', models.BooleanField(default=False)),
                ('kind', models.CharField(help_text='A programme DocumentKind value — resolved in code.', max_length=50)),
                ('storage_key', models.CharField(editable=False, max_length=255)),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size', models.PositiveIntegerField()),
                ('sha256', models.CharField(editable=False, max_length=64)),
            ],
            options={
                'ordering': ['created_date'],
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='ApplicationFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('form_key', models.CharField(max_length=50)),
                ('round', models.PositiveIntegerField(help_text='Stamped from Application.round at write time.')),
                ('data', models.JSONField(help_text='form.cleaned_data, never raw POST.')),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('is_current', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_date'],
                'default_manager_name': 'objects',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='round',
            field=models.PositiveIntegerField(default=1, help_text='Review cycle; advanced only by round-advancing transitions.'),
        ),
        migrations.AddField(
            model_name='application',
            name='workflow_key',
            field=models.CharField(default='', help_text='Resolved against sandbox.workflow.registry — never a CHECK. Empty only on pre-port rows; the cutover migration backfills it.', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), models.Q(('state__in', ('REJECTED', 'WITHDRAWN', 'APPROVED')), _negated=True)), fields=('product', 'workflow_key'), name='applications_one_in_flight_per_product_workflow'),
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationformsubmission',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='applications.application'),
        ),
        migrations.AddField(
            model_name='applicationformsubmission',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='form_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='applications.applicationformsubmission'),
        ),
        migrations.AddIndex(
            model_name='applicationformsubmission',
            index=models.Index(fields=['application', 'form_key'], name='applications_afs_app_form_idx'),
        ),
        migrations.AddConstraint(
            model_name='applicationformsubmission',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('application', 'form_key'), name='applications_one_current_submission'),
        ),
        migrations.AddConstraint(
            model_name='applicationdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('storage_key',), name='applications_document_unique_storage_key'),
        ),
    ]
