# Generated by Django 6.0.8 on 2026-08-31 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_afs_append_only'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='application',
            name='applications_application_kind_valid',
        ),
        migrations.RemoveConstraint(
            model_name='application',
            name='applications_application_state_valid',
        ),
    ]
