# Generated by Django 6.0.8 on 2026-08-31 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_drop_enum_checks'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='application',
            name='applications_application_unique_live_product_kind',
        ),
    ]
