# Generated by Django 6.0.8 on 2026-08-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_drop_live_product_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='payload',
            field=models.JSONField(default=dict),
        ),
    ]
