# Generated by Django 6.0.8 on 2026-08-31 17:36

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_payload_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationformsubmission',
            name='data',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='form.cleaned_data, never raw POST.'),
        ),
    ]
