# Generated by Django 6.0.8 on 2026-08-31 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_submission_json_encoder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='state',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('SANDBOX_APPROVED', 'Sandbox approved'), ('PROVISIONING', 'Provisioning'), ('PROVISIONED', 'Provisioned'), ('PROVISIONING_FAILED', 'Provisioning failed'), ('REJECTED', 'Rejected'), ('SENT_BACK', 'Sent back'), ('WITHDRAWN', 'Withdrawn')], default='DRAFT', max_length=30),
        ),
    ]
