# Generated by Django 6.0.8 on 2026-08-31 20:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_drop_declaration_tables'),
        ('organisations', '0002_organisation_category_organisation_gst_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='application',
            name='applications_kind_state_idx',
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['workflow_key', 'state'], name='applications_wf_state_idx'),
        ),
        migrations.RemoveField(
            model_name='application',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='application',
            name='payload',
        ),
    ]
