# Generated by Django 6.0.8 on 2026-09-01 18:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_drop_kind_and_payload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='applicationdocument',
            name='applications_document_unique_storage_key',
        ),
        migrations.AddConstraint(
            model_name='applicationdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('submission', 'storage_key'), name='applications_document_unique_storage_key'),
        ),
    ]
