# Generated by Django 6.0.8 on 2026-08-30 07:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0002_rename_kind_state_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted', models.BooleanField(default=False)),
                ('recipient', models.CharField(max_length=254)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS')], default='EMAIL', max_length=10)),
                ('template_key', models.CharField(choices=[('send-otp', 'Send OTP'), ('sandbox-approved', 'Sandbox approved'), ('sandbox-rejected', 'Sandbox rejected'), ('exit-sent-back', 'Exit sent back'), ('exit-rejected', 'Exit rejected'), ('production-approved', 'Production approved')], max_length=50)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('state', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=100)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='applications.application')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
                'indexes': [models.Index(fields=['state', 'created_date'], name='notifications_state_idx'), models.Index(fields=['application', '-created_date'], name='notifications_app_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('channel__in', ['EMAIL', 'SMS'])), name='notifications_message_channel_valid'), models.CheckConstraint(condition=models.Q(('state__in', ['PENDING', 'SENT', 'FAILED'])), name='notifications_message_state_valid'), models.CheckConstraint(condition=models.Q(('template_key__in', ['send-otp', 'sandbox-approved', 'sandbox-rejected', 'exit-sent-back', 'exit-rejected', 'production-approved'])), name='notifications_message_template_key_valid')],
            },
        ),
    ]
