# Generated by Django 6.0.8 on 2026-09-06 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['state', 'created_date'], name='notifications_state_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['application', '-created_date'], name='notifications_app_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('channel__in', ['EMAIL', 'SMS'])), name='notifications_message_channel_valid'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['PENDING', 'SENT', 'FAILED'])), name='notifications_message_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('template_key__in', ['send-otp', 'sandbox-approved', 'sandbox-rejected', 'exit-sent-back', 'exit-rejected', 'production-approved'])), name='notifications_message_template_key_valid'),
        ),
    ]
