# Generated by Django 6.0.8 on 2026-08-28 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0003_sandbox'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=40, unique=True, verbose_name='Reference')),
                ('application_type', models.CharField(db_index=True, max_length=100, verbose_name='Application type')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('status', models.CharField(db_index=True, max_length=50, verbose_name='Status')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('outcome', models.JSONField(blank=True, default=dict, verbose_name='Outcome')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_experience_applications', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_experience_applications', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experience_applications', to='organisations.organisation')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_key', models.CharField(max_length=100, verbose_name='Form key')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('needs_changes', 'Needs changes')], default='completed', max_length=30, verbose_name='Status')),
                ('data', models.JSONField(default=dict, verbose_name='Validated data')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experience_form_submissions', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='experiences.applicationinstance')),
            ],
            options={
                'ordering': ['submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('created', 'Created'), ('form_submitted', 'Form submitted'), ('action', 'Action'), ('status_changed', 'Status changed'), ('access_changed', 'Access changed'), ('query', 'Query')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('action_key', models.CharField(blank=True, max_length=100)),
                ('status_before', models.CharField(blank=True, max_length=50)),
                ('status_after', models.CharField(blank=True, max_length=50)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experience_events', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='experiences.applicationformsubmission')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='experiences.applicationinstance')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_key', models.CharField(blank=True, max_length=80, verbose_name='Application role')),
                ('direct_permissions', models.JSONField(blank=True, default=list, verbose_name='Additional permissions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_experience_access', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_access_grants', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='experiences.applicationinstance')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationQueryThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('awaiting_applicant', 'Awaiting applicant'), ('answered', 'Answered'), ('resolved', 'Resolved')], db_index=True, default='awaiting_applicant', max_length=30)),
                ('due_at', models.DateField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_threads', to='experiences.applicationinstance')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_application_queries', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_application_queries', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='query_threads', to='experiences.applicationformsubmission')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationQueryMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('kind', models.CharField(choices=[('message', 'Message'), ('event', 'Event')], default='message', max_length=20)),
                ('is_internal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='application_query_messages', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='experiences.applicationquerythread')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='experience-attachments/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=150)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experience_attachments', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='experiences.applicationformsubmission')),
            ],
            options={
                'ordering': ['field_key', '-created_at'],
                'indexes': [models.Index(fields=['submission', 'field_key', 'is_current'], name='exp_current_attachment_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='applicationinstance',
            index=models.Index(fields=['organisation', 'application_type', 'status'], name='experience_org_type_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='applicationformsubmission',
            constraint=models.UniqueConstraint(fields=('application', 'form_key'), name='unique_experience_form_per_application'),
        ),
        migrations.AddConstraint(
            model_name='applicationaccess',
            constraint=models.UniqueConstraint(fields=('application', 'user'), name='unique_user_access_per_application'),
        ),
    ]
