# Generated by Django 6.0.8 on 2026-09-06 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiences', '0001_initial'),
        ('organisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationaccess',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_experience_access', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_access_grants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationattachment',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experience_attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experience_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationformsubmission',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experience_form_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationevent',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='experiences.applicationformsubmission'),
        ),
        migrations.AddField(
            model_name='applicationattachment',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='experiences.applicationformsubmission'),
        ),
        migrations.AddField(
            model_name='applicationinstance',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_experience_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationinstance',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_experience_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationinstance',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experience_applications', to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='applicationformsubmission',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='experiences.applicationinstance'),
        ),
        migrations.AddField(
            model_name='applicationevent',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='experiences.applicationinstance'),
        ),
        migrations.AddField(
            model_name='applicationaccess',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='experiences.applicationinstance'),
        ),
        migrations.AddField(
            model_name='applicationquerymessage',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='application_query_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationquerythread',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_threads', to='experiences.applicationinstance'),
        ),
        migrations.AddField(
            model_name='applicationquerythread',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_application_queries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationquerythread',
            name='opened_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_application_queries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationquerythread',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='query_threads', to='experiences.applicationformsubmission'),
        ),
        migrations.AddField(
            model_name='applicationquerymessage',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='experiences.applicationquerythread'),
        ),
        migrations.AddIndex(
            model_name='applicationattachment',
            index=models.Index(fields=['submission', 'field_key', 'is_current'], name='exp_current_attachment_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationinstance',
            index=models.Index(fields=['organisation', 'application_type', 'status'], name='experience_org_type_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='applicationformsubmission',
            constraint=models.UniqueConstraint(fields=('application', 'form_key', 'submission_number', 'revision'), name='unique_experience_form_submission_revision'),
        ),
        migrations.AddConstraint(
            model_name='applicationformsubmission',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('application', 'form_key'), name='unique_current_experience_form_submission'),
        ),
        migrations.AddConstraint(
            model_name='applicationaccess',
            constraint=models.UniqueConstraint(fields=('application', 'user'), name='unique_user_access_per_application'),
        ),
    ]
