# Generated by Django 6.0.8 on 2026-08-28 20:49

from django.db import migrations, models


def move_answered_queries_forward(apps, schema_editor):
    query_thread = apps.get_model("experiences", "ApplicationQueryThread")
    query_thread.objects.filter(status="answered").update(
        status="awaiting_reviewer",
    )


def move_answered_queries_backward(apps, schema_editor):
    query_thread = apps.get_model("experiences", "ApplicationQueryThread")
    query_thread.objects.filter(status="awaiting_reviewer").update(
        status="answered",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            move_answered_queries_forward,
            move_answered_queries_backward,
        ),
        migrations.AlterField(
            model_name='applicationquerythread',
            name='status',
            field=models.CharField(choices=[('awaiting_applicant', 'Awaiting applicant'), ('awaiting_reviewer', 'Awaiting reviewer'), ('resolved', 'Resolved')], db_index=True, default='awaiting_applicant', max_length=30),
        ),
    ]
