# Generated by Django 6.0.8 on 2026-08-30 07:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0002_alter_applicationquerythread_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationformsubmission',
            options={'ordering': ['form_key', '-submission_number']},
        ),
        migrations.RemoveConstraint(
            model_name='applicationformsubmission',
            name='unique_experience_form_per_application',
        ),
        migrations.AddField(
            model_name='applicationformsubmission',
            name='is_current',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='applicationformsubmission',
            name='submission_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='applicationformsubmission',
            name='valid_until',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='applicationformsubmission',
            constraint=models.UniqueConstraint(fields=('application', 'form_key', 'submission_number'), name='unique_experience_form_submission_number'),
        ),
        migrations.AddConstraint(
            model_name='applicationformsubmission',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('application', 'form_key'), name='unique_current_experience_form_submission'),
        ),
    ]
