# Generated by Django 6.0.8 on 2026-09-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0004_seed_review_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationevent',
            name='is_internal',
            field=models.BooleanField(default=False, verbose_name='Internal'),
        ),
    ]
