# Generated by Django 6.0.8 on 2026-09-08 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0005_applicationevent_is_internal'),
        ('organisations', '0007_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationinstance',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='organisations.product', verbose_name='Product'),
        ),
    ]
