# Generated by Django 6.0.8 on 2026-08-29 13:09

import django.db.models.deletion
import sandbox.workflow.machine
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_state', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('SANDBOX_APPROVED', 'Sandbox approved'), ('PROVISIONING', 'Provisioning'), ('PROVISIONED', 'Provisioned'), ('PROVISIONING_FAILED', 'Provisioning failed'), ('REJECTED', 'Rejected'), ('SENT_BACK', 'Sent back'), ('EXIT_REQUESTED', 'Exit requested'), ('EXIT_REVIEW', 'Exit review'), ('PRODUCTION_APPROVED', 'Production approved'), ('EXIT_REJECTED', 'Exit rejected'), ('WITHDRAWN', 'Withdrawn')], max_length=30)),
                ('to_state', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('SANDBOX_APPROVED', 'Sandbox approved'), ('PROVISIONING', 'Provisioning'), ('PROVISIONED', 'Provisioned'), ('PROVISIONING_FAILED', 'Provisioning failed'), ('REJECTED', 'Rejected'), ('SENT_BACK', 'Sent back'), ('EXIT_REQUESTED', 'Exit requested'), ('EXIT_REVIEW', 'Exit review'), ('PRODUCTION_APPROVED', 'Production approved'), ('EXIT_REJECTED', 'Exit rejected'), ('WITHDRAWN', 'Withdrawn')], max_length=30)),
                ('action', models.CharField(choices=[(sandbox.workflow.machine.Action['SUBMIT'], sandbox.workflow.machine.Action['SUBMIT']), (sandbox.workflow.machine.Action['APPROVE'], sandbox.workflow.machine.Action['APPROVE']), (sandbox.workflow.machine.Action['REJECT'], sandbox.workflow.machine.Action['REJECT']), (sandbox.workflow.machine.Action['SEND_BACK'], sandbox.workflow.machine.Action['SEND_BACK']), (sandbox.workflow.machine.Action['WITHDRAW'], sandbox.workflow.machine.Action['WITHDRAW']), (sandbox.workflow.machine.Action['START_PROVISIONING'], sandbox.workflow.machine.Action['START_PROVISIONING']), (sandbox.workflow.machine.Action['COMPLETE_PROVISIONING'], sandbox.workflow.machine.Action['COMPLETE_PROVISIONING']), (sandbox.workflow.machine.Action['FAIL_PROVISIONING'], sandbox.workflow.machine.Action['FAIL_PROVISIONING']), (sandbox.workflow.machine.Action['RETRY_PROVISIONING'], sandbox.workflow.machine.Action['RETRY_PROVISIONING']), (sandbox.workflow.machine.Action['REQUEST_EXIT'], sandbox.workflow.machine.Action['REQUEST_EXIT']), (sandbox.workflow.machine.Action['START_EXIT_REVIEW'], sandbox.workflow.machine.Action['START_EXIT_REVIEW']), (sandbox.workflow.machine.Action['APPROVE_EXIT'], sandbox.workflow.machine.Action['APPROVE_EXIT']), (sandbox.workflow.machine.Action['REJECT_EXIT'], sandbox.workflow.machine.Action['REJECT_EXIT']), (sandbox.workflow.machine.Action['SEND_BACK_EXIT'], sandbox.workflow.machine.Action['SEND_BACK_EXIT'])], max_length=30)),
                ('comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Null for system moves such as chain completion.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_transitions', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitions', to='applications.application')),
            ],
            options={
                'ordering': ['-created_date'],
                'permissions': [('approve_application', 'Can approve an application'), ('reject_application', 'Can reject an application'), ('review_application', 'Can send back or start an exit review'), ('retry_provisioning', 'Can retry a failed provisioning chain')],
                'indexes': [models.Index(fields=['application', '-created_date'], name='workflow_transition_app_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('from_state__in', ['DRAFT', 'SUBMITTED', 'SANDBOX_APPROVED', 'PROVISIONING', 'PROVISIONED', 'PROVISIONING_FAILED', 'REJECTED', 'SENT_BACK', 'EXIT_REQUESTED', 'EXIT_REVIEW', 'PRODUCTION_APPROVED', 'EXIT_REJECTED', 'WITHDRAWN'])), name='workflow_transition_from_state_valid'), models.CheckConstraint(condition=models.Q(('to_state__in', ['DRAFT', 'SUBMITTED', 'SANDBOX_APPROVED', 'PROVISIONING', 'PROVISIONED', 'PROVISIONING_FAILED', 'REJECTED', 'SENT_BACK', 'EXIT_REQUESTED', 'EXIT_REVIEW', 'PRODUCTION_APPROVED', 'EXIT_REJECTED', 'WITHDRAWN'])), name='workflow_transition_to_state_valid'), models.CheckConstraint(condition=models.Q(('action__in', ['SUBMIT', 'APPROVE', 'REJECT', 'SEND_BACK', 'WITHDRAW', 'START_PROVISIONING', 'COMPLETE_PROVISIONING', 'FAIL_PROVISIONING', 'RETRY_PROVISIONING', 'REQUEST_EXIT', 'START_EXIT_REVIEW', 'APPROVE_EXIT', 'REJECT_EXIT', 'SEND_BACK_EXIT'])), name='workflow_transition_action_valid')],
            },
        ),
    ]
