# Generated by Django 6.0.8 on 2026-08-29 14:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_rename_kind_state_index'),
        ('workflow', '0002_append_only'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted', models.BooleanField(default=False)),
                ('round', models.PositiveIntegerField(default=1)),
                ('decision', models.CharField(choices=[('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('SEND_BACK', 'Send back')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='applications.application')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-decided_at'],
                'indexes': [models.Index(fields=['application', 'round'], name='workflow_review_round_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('application', 'reviewer', 'round'), name='workflow_review_unique_per_round'), models.CheckConstraint(condition=models.Q(('decision__in', ['APPROVE', 'REJECT', 'SEND_BACK'])), name='workflow_review_decision_valid')],
            },
        ),
    ]
