# Generated by Django 6.0.8 on 2026-08-29 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_workflow_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflowtransition',
            options={'ordering': ['-created_date'], 'permissions': [('approve_application', 'Can approve an application'), ('reject_application', 'Can reject an application'), ('send_back_application', 'Can return an application to the applicant'), ('review_application', 'Can record a review (moves nothing)'), ('retry_provisioning', 'Can retry a failed provisioning chain')]},
        ),
    ]
