# Generated by Django 6.0.8 on 2026-08-31 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_split_send_back_permission'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workflowtransition',
            name='workflow_transition_from_state_valid',
        ),
        migrations.RemoveConstraint(
            model_name='workflowtransition',
            name='workflow_transition_to_state_valid',
        ),
        migrations.RemoveConstraint(
            model_name='workflowtransition',
            name='workflow_transition_action_valid',
        ),
        migrations.AlterField(
            model_name='workflowtransition',
            name='action',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='workflowtransition',
            name='from_state',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='workflowtransition',
            name='to_state',
            field=models.CharField(max_length=40),
        ),
    ]
