# Generated by Django 6.0.8 on 2026-09-01 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_drop_enum_checks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflowtransition',
            options={'ordering': ['-created_date']},
        ),
    ]
